In [3]:
import pandas as pd
import numpy as np
import itertools

# Lista de las 10 variables usadas
variables = [
    "Temperatura de la muestra",
    "pH",
    "Conductividad eléctrica",
    "Sólidos totales disueltos",
    "Sólidos totales suspendidos",
    "Oxígeno disuelto",
    "Nivel del río",
    "Turbidez",
    "Dureza",
    "Cloruros"
]

# Hay C(10,2) = 45 combinaciones únicas de pares
num_variables = len(variables)
num_comparisons = num_variables * (num_variables - 1) // 2  # rango *(rango -1)/2

# Mostramos los pares a comparar
pairwise_comparisons = list(itertools.combinations(variables, 2))

(num_comparisons, pairwise_comparisons[:45])  # mostramos las 45 comparaciones posibles

(45,
 [('Temperatura de la muestra', 'pH'),
  ('Temperatura de la muestra', 'Conductividad eléctrica'),
  ('Temperatura de la muestra', 'Sólidos totales disueltos'),
  ('Temperatura de la muestra', 'Sólidos totales suspendidos'),
  ('Temperatura de la muestra', 'Oxígeno disuelto'),
  ('Temperatura de la muestra', 'Nivel del río'),
  ('Temperatura de la muestra', 'Turbidez'),
  ('Temperatura de la muestra', 'Dureza'),
  ('Temperatura de la muestra', 'Cloruros'),
  ('pH', 'Conductividad eléctrica'),
  ('pH', 'Sólidos totales disueltos'),
  ('pH', 'Sólidos totales suspendidos'),
  ('pH', 'Oxígeno disuelto'),
  ('pH', 'Nivel del río'),
  ('pH', 'Turbidez'),
  ('pH', 'Dureza'),
  ('pH', 'Cloruros'),
  ('Conductividad eléctrica', 'Sólidos totales disueltos'),
  ('Conductividad eléctrica', 'Sólidos totales suspendidos'),
  ('Conductividad eléctrica', 'Oxígeno disuelto'),
  ('Conductividad eléctrica', 'Nivel del río'),
  ('Conductividad eléctrica', 'Turbidez'),
  ('Conductividad eléctrica', 'Dureza'),
  ('Conductividad eléctrica', 'Cloruros'),
  ('Sólidos totales disueltos', 'Sólidos totales suspendidos'),
  ('Sólidos totales disueltos', 'Oxígeno disuelto'),
  ('Sólidos totales disueltos', 'Nivel del río'),
  ('Sólidos totales disueltos', 'Turbidez'),
  ('Sólidos totales disueltos', 'Dureza'),
  ('Sólidos totales disueltos', 'Cloruros'),
  ('Sólidos totales suspendidos', 'Oxígeno disuelto'),
  ('Sólidos totales suspendidos', 'Nivel del río'),
  ('Sólidos totales suspendidos', 'Turbidez'),
  ('Sólidos totales suspendidos', 'Dureza'),
  ('Sólidos totales suspendidos', 'Cloruros'),
  ('Oxígeno disuelto', 'Nivel del río'),
  ('Oxígeno disuelto', 'Turbidez'),
  ('Oxígeno disuelto', 'Dureza'),
  ('Oxígeno disuelto', 'Cloruros'),
  ('Nivel del río', 'Turbidez'),
  ('Nivel del río', 'Dureza'),
  ('Nivel del río', 'Cloruros'),
  ('Turbidez', 'Dureza'),
  ('Turbidez', 'Cloruros'),
  ('Dureza', 'Cloruros')])

In [21]:
# Inicializamos una matriz de 10x10 con unos en la diagonal principal
n = len(variables)
comparison_matrix = np.ones((n, n))

# Diccionario auxiliar para encontrar índices
var_idx = {var: i for i, var in enumerate(variables)}

# Función para asignar valores a la matriz de comparación (usando criterios recreativos y ecológicos)
def set_comparison(var1, var2, value):
    i, j = var_idx[var1], var_idx[var2]
    comparison_matrix[i][j] = value
    comparison_matrix[j][i] = 1 / value

# Asignamos valores según criterios expertos:
# Variables más importantes como Oxígeno Disuelto y pH tendrán más peso.
# Valores de Thomas Saaty (1980), con inversos donde corresponde!!!!!
#Criterios utilizados para valorar
# Los criterios se basan en fuentes como:

# OMS (Organización Mundial de la Salud)

# EPA (Agencia de Protección Ambiental de EE. UU.)

# Normas IRAM y legislación argentina para agua recreativa

# Estudios científicos sobre calidad ecológica de cuerpos de agua


                                    #(decantan)
# od > pH > std >= ce > turbidez > sts > nivel > cloruros > dureza > temp

set_comparison("Oxígeno disuelto", "pH", 3) 
set_comparison("Oxígeno disuelto", "Conductividad eléctrica", 4) 
set_comparison("Oxígeno disuelto", "Sólidos totales disueltos", 4)
set_comparison("Oxígeno disuelto", "Sólidos totales suspendidos", 5) 
set_comparison("Oxígeno disuelto", "Temperatura de la muestra", 7) 
set_comparison("Oxígeno disuelto", "Nivel del río", 5) 
set_comparison("Oxígeno disuelto", "Turbidez", 5) 
set_comparison("Oxígeno disuelto", "Dureza", 6)
set_comparison("Oxígeno disuelto", "Cloruros", 6)

set_comparison("Turbidez", "pH", 1/3) 
set_comparison("Turbidez", "Conductividad eléctrica", 1/2) 
set_comparison("Turbidez", "Sólidos totales disueltos", 1/2) 
set_comparison("Turbidez", "Sólidos totales suspendidos", 2)
set_comparison("Turbidez", "Temperatura de la muestra", 5) 
set_comparison("Turbidez", "Nivel del río", 3)
set_comparison("Turbidez", "Dureza", 4)
set_comparison("Turbidez", "Cloruros", 4)

set_comparison("pH", "Conductividad eléctrica", 3) 
set_comparison("pH", "Sólidos totales disueltos", 3) 
set_comparison("pH", "Sólidos totales suspendidos", 4) 
set_comparison("pH", "Temperatura de la muestra", 7) 
set_comparison("pH", "Nivel del río", 5) 
set_comparison("pH", "Dureza", 6)
set_comparison("pH", "Cloruros", 6) 

set_comparison("Temperatura de la muestra", "Conductividad eléctrica", 1/5)
set_comparison("Temperatura de la muestra", "Sólidos totales disueltos", 1/5) 
set_comparison("Temperatura de la muestra", "Sólidos totales suspendidos", 1/4) 
set_comparison("Temperatura de la muestra", "Nivel del río", 1/3) 
set_comparison("Temperatura de la muestra", "Dureza", 1/2) 
set_comparison("Temperatura de la muestra", "Cloruros", 1/2) 

set_comparison("Conductividad eléctrica", "Sólidos totales disueltos", 1) 
set_comparison("Conductividad eléctrica", "Sólidos totales suspendidos", 3) 
set_comparison("Conductividad eléctrica", "Nivel del río", 4) 
set_comparison("Conductividad eléctrica", "Dureza", 5)
set_comparison("Conductividad eléctrica", "Cloruros", 5)

set_comparison("Sólidos totales disueltos", "Sólidos totales suspendidos", 2)
set_comparison("Sólidos totales disueltos", "Nivel del río", 3) 
set_comparison("Sólidos totales disueltos", "Dureza", 4) 
set_comparison("Sólidos totales disueltos", "Cloruros", 4)

set_comparison("Sólidos totales suspendidos", "Nivel del río", 1)
set_comparison("Sólidos totales suspendidos", "Dureza", 2)
set_comparison("Sólidos totales suspendidos", "Cloruros", 2) 

set_comparison("Nivel del río", "Dureza", 2) 
set_comparison("Nivel del río", "Cloruros", 2)

set_comparison("Dureza", "Cloruros", 1/2)

#####################################################################################
#####################################################################################

# Pasamos a DataFrame para mejor visualización
comparison_df = pd.DataFrame(comparison_matrix, index=variables, columns=variables)
comparison_df.round(3)

,Temperatura de la muestra,pH,Conductividad eléctrica,Sólidos totales disueltos,Sólidos totales suspendidos,Oxígeno disuelto,Nivel del río,Turbidez,Dureza,Cloruros
Temperatura de la muestra,1.0,0.143,0.200,0.200,0.25,0.143,0.333,0.200,0.5,0.5
pH,7.0,1.000,3.000,3.000,4.00,0.333,5.000,3.000,6.0,6.0
Conductividad eléctrica,5.0,0.333,1.000,1.000,3.00,0.250,4.000,2.000,5.0,5.0
Sólidos totales disueltos,5.0,0.333,1.000,1.000,2.00,0.250,3.000,2.000,4.0,4.0
Sólidos totales suspendidos,4.0,0.250,0.333,0.500,1.00,0.200,1.000,0.500,2.0,2.0
Oxígeno disuelto,7.0,3.000,4.000,4.000,5.00,1.000,5.000,5.000,6.0,6.0
Nivel del río,3.0,0.200,0.250,0.333,1.00,0.200,1.000,0.333,2.0,2.0
Turbidez,5.0,0.333,0.500,0.500,2.00,0.200,3.000,1.000,4.0,4.0
Dureza,2.0,0.167,0.200,0.250,0.50,0.167,0.500,0.250,1.0,0.5
Cloruros,2.0,0.167,0.200,0.250,0.50,0.167,0.500,0.250,2.0,1.0

In [8]:
# Reimportación de librerías después del reset del entorno
import numpy as np
import pandas as pd

# Variables definidas por el usuario
variables = [
    "Temperatura de la muestra",
    "pH",
    "Conductividad eléctrica",
    "Sólidos totales disueltos",
    "Sólidos totales suspendidos",
    "Oxígeno disuelto",
    "Nivel del río",
    "Turbidez",
    "Dureza",
    "Cloruros"
]

n = len(variables)
comparison_matrix = np.ones((n, n))
var_idx = {var: i for i, var in enumerate(variables)}

def set_comparison(var1, var2, value):
    i, j = var_idx[var1], var_idx[var2]
    comparison_matrix[i][j] = value
    comparison_matrix[j][i] = 1 / value

# Comparaciones proporcionadas
set_comparison("Oxígeno disuelto", "pH", 3) 
set_comparison("Oxígeno disuelto", "Conductividad eléctrica", 4) 
set_comparison("Oxígeno disuelto", "Sólidos totales disueltos", 4)
set_comparison("Oxígeno disuelto", "Sólidos totales suspendidos", 5) 
set_comparison("Oxígeno disuelto", "Temperatura de la muestra", 7) 
set_comparison("Oxígeno disuelto", "Nivel del río", 5) 
set_comparison("Oxígeno disuelto", "Turbidez", 5) 
set_comparison("Oxígeno disuelto", "Dureza", 6)
set_comparison("Oxígeno disuelto", "Cloruros", 6)

set_comparison("Turbidez", "pH", 1/3) 
set_comparison("Turbidez", "Conductividad eléctrica", 1/2) 
set_comparison("Turbidez", "Sólidos totales disueltos", 1/2) 
set_comparison("Turbidez", "Sólidos totales suspendidos", 2)
set_comparison("Turbidez", "Temperatura de la muestra", 5) 
set_comparison("Turbidez", "Nivel del río", 3)
set_comparison("Turbidez", "Dureza", 4)
set_comparison("Turbidez", "Cloruros", 4)

set_comparison("pH", "Conductividad eléctrica", 3) 
set_comparison("pH", "Sólidos totales disueltos", 3) 
set_comparison("pH", "Sólidos totales suspendidos", 4) 
set_comparison("pH", "Temperatura de la muestra", 7) 
set_comparison("pH", "Nivel del río", 5) 
set_comparison("pH", "Dureza", 6)
set_comparison("pH", "Cloruros", 6) 

set_comparison("Temperatura de la muestra", "Conductividad eléctrica", 1/5)
set_comparison("Temperatura de la muestra", "Sólidos totales disueltos", 1/5) 
set_comparison("Temperatura de la muestra", "Sólidos totales suspendidos", 1/4) 
set_comparison("Temperatura de la muestra", "Nivel del río", 1/3) 
set_comparison("Temperatura de la muestra", "Dureza", 1/2) 
set_comparison("Temperatura de la muestra", "Cloruros", 1/2) 

set_comparison("Conductividad eléctrica", "Sólidos totales disueltos", 1) 
set_comparison("Conductividad eléctrica", "Sólidos totales suspendidos", 3) 
set_comparison("Conductividad eléctrica", "Nivel del río", 4) 
set_comparison("Conductividad eléctrica", "Dureza", 5)
set_comparison("Conductividad eléctrica", "Cloruros", 5)

set_comparison("Sólidos totales disueltos", "Sólidos totales suspendidos", 2)
set_comparison("Sólidos totales disueltos", "Nivel del río", 3) 
set_comparison("Sólidos totales disueltos", "Dureza", 4) 
set_comparison("Sólidos totales disueltos", "Cloruros", 4)

set_comparison("Sólidos totales suspendidos", "Nivel del río", 1)
set_comparison("Sólidos totales suspendidos", "Dureza", 2)
set_comparison("Sólidos totales suspendidos", "Cloruros", 2) 

set_comparison("Nivel del río", "Dureza", 2) 
set_comparison("Nivel del río", "Cloruros", 2)

set_comparison("Dureza", "Cloruros", 1/2)

# Normalización de la matriz (división columna por suma de columna)
column_sums = comparison_matrix.sum(axis=0)
normalized_matrix = comparison_matrix / column_sums

# Promedio de cada fila (autovector aproximado)
weights = normalized_matrix.mean(axis=1)

# DataFrame con resultados
weights_df = pd.DataFrame({
    "Variable": variables,
    "Peso": weights
})

weights_df = weights_df.sort_values(by="Peso", ascending=False).reset_index(drop=True).round(4)
weights_df

                      Variable    Peso
0             Oxígeno disuelto  0.2954
1                           pH  0.2013
2      Conductividad eléctrica  0.1228
3    Sólidos totales disueltos  0.1071
4                     Turbidez  0.0892
5  Sólidos totales suspendidos  0.0540
6                Nivel del río  0.0473
7                     Cloruros  0.0334
8                       Dureza  0.0287
9    Temperatura de la muestra  0.0207

In [20]:
import numpy as np

def calcular_pesos_y_consistencia(matrix):
    n = matrix.shape[0]

    # Paso 1: Normalización por columnas
    col_sum = matrix.sum(axis=0)
    normalized_matrix = matrix / col_sum

    # Paso 2: Promedio de filas → pesos aproximados
    weights = normalized_matrix.mean(axis=1)

    # Paso 3: Autovalor máximo λ_max aproximado
    # Cuando A⋅w=n⋅w si es perfectamente consistente (n es autovalor y w autovector de pesos)
    # caso contrario λ_max.w
    
    Aw = matrix @ weights
    lambda_max = np.sum(Aw / weights) / n

    # Paso 4: Índice de consistencia CI
    CI = (lambda_max - n) / (n - 1)

    # Paso 5: Índice Aleatorio RI según Saaty
    RI_dict = {1: 0.00, 2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12,
               6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
    RI = RI_dict.get(n, None)

    if RI is not None and RI != 0:
        CR = CI / RI
    else:
        CR = 0

    return weights, lambda_max, CI, CR

# Aplicando a la matriz de comparación `comparison_matrix` obtenemos:

pesos, lambda_max, CI, CR = calcular_pesos_y_consistencia(comparison_matrix)

# Mostrar resultados
for i, var in enumerate(variables):
    print(f"{var:30} Peso: {pesos[i]:.4f}")

print(f"\nλ_max = {lambda_max:.4f}")
print(f"CI = {CI:.4f}")
print(f"CR = {CR:.4f} → {'Consistente' if CR < 0.1 else 'Inconsistente'}")

Temperatura de la muestra      Peso: 0.0207
pH                             Peso: 0.2013
Conductividad eléctrica        Peso: 0.1228
Sólidos totales disueltos      Peso: 0.1071
Sólidos totales suspendidos    Peso: 0.0540
Oxígeno disuelto               Peso: 0.2954
Nivel del río                  Peso: 0.0473
Turbidez                       Peso: 0.0892
Dureza                         Peso: 0.0287
Cloruros                       Peso: 0.0334

λ_max = 10.5444
CI = 0.0605
CR = 0.0406 → Consistente